"""Citizen contamination reports.

What this does, exactly
-----------------------
1. Builds a human-readable report from an observation the user explicitly chose to submit.
2. Writes it to this backend's own report log (JSONL, one file per month) with any evidence photo.
3. Forwards it to a destination ONLY when one is configured (ECOSENTINEL_AUTHORITY_WEBHOOK_URL).

What this does NOT do
---------------------
It does not know any real pollution-control board, and it never claims a report reached one. With
no destination configured, the receipt says `recorded` and states plainly that nothing was
transmitted, so the user can send the text themselves. A failed forward is reported as
`forward_failed`, never quietly downgraded to success.

PRIVACY: this is the one place in the backend that persists precise coordinates. That is the point
of a report, it only happens on an explicit per-report confirmation in the UI, and the stored record
is exactly what the reporter was shown before confirming.
"""

import base64
import binascii
import json
import re
import secrets
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Tuple

from config import settings
from schemas import ContaminationReportReceipt, ContaminationReportRequest
from services.overpass_service import nearest_water_body

DATA_URI = re.compile(r"^data:image/(?P<kind>[a-zA-Z0-9.+-]+);base64,(?P<payload>.+)$", re.DOTALL)
MAX_PHOTO_BYTES = 6 * 1024 * 1024
_write_lock = threading.Lock()


def _reference() -> str:
    return f"ECO-{datetime.now(timezone.utc):%Y%m%d}-{secrets.token_hex(3).upper()}"


def _coordinates(latitude: float, longitude: float) -> str:
    return f"{latitude:.5f}, {longitude:.5f}"


def build_summary(request: ContaminationReportRequest, reference: str, water_body: Optional[str] = None) -> str:
    """The exact text stored, forwarded and shown to the reporter — one source of truth.

    The matcher's caveat is part of the report body on purpose: a recipient must not read
    "resembles contaminated reference frames" as a laboratory result.
    """
    location = request.location
    match = request.match
    place = location.display_name or ", ".join(
        part for part in (location.neighbourhood, location.city, location.state, location.country) if part
    ) or "Unnamed location"

    lines = [
        f"WATER CONTAMINATION REPORT · {reference}",
        "",
        f"Observed at   : {request.observed_at.isoformat()}",
        f"Submitted at  : {datetime.now(timezone.utc).isoformat()}",
        f"Place         : {place}",
        f"Coordinates   : {_coordinates(location.latitude, location.longitude)}",
    ]
    if location.accuracy_m is not None:
        lines.append(f"GPS accuracy  : ±{location.accuracy_m:.0f} m")
    if location.water_feature:
        lines.append(f"Water feature : {location.water_feature}")
    lines.append(f"Evidence      : {'live camera frame' if request.source == 'camera' else 'uploaded photo'}")
    if water_body:
        lines.append(f"Nearest mapped water body : {water_body}")

    lines += ["", "VISUAL ASSESSMENT (automated, appearance-based)"]
    if match.status == "ok" and match.matched_label:
        lines.append(f"  Resembles reference class : {match.matched_label} ({match.matched_class})")
        if match.similarity is not None:
            lines.append(f"  Best similarity           : {match.similarity:.2f}")
        if match.vote_share is not None:
            lines.append(f"  Nearest-neighbour vote    : {match.vote_share:.0%}")
        if match.near_duplicate and match.duplicate_of:
            lines.append(f"  NOTE: near-duplicate of reference frame {match.duplicate_of} — possibly a replayed sample")
        for neighbour in match.neighbours[:3]:
            lines.append(f"    - {neighbour.file} ({neighbour.label}) {neighbour.similarity:.2f}")
    else:
        lines.append(f"  No confident reference match ({match.status}).")
    if match.caveat:
        lines += ["", "  RELIABILITY OF THE ABOVE:", f"    {match.caveat}"]

    if request.water_risk_level or request.water_risk_score is not None:
        lines += ["", "WATER AGENT ASSESSMENT (sensor/dataset readings)"]
        if request.water_risk_level:
            lines.append(f"  Risk level : {request.water_risk_level}")
        if request.water_risk_score is not None:
            lines.append(f"  Risk score : {request.water_risk_score:.0%}")

    if request.note:
        lines += ["", "REPORTER'S NOTE", f"  {request.note}"]
    lines += ["", f"Reporter contact: {request.contact or 'not provided'}"]
    lines += [
        "",
        "Generated by EcoSentinel AI. The visual assessment is an automated appearance match and",
        "is not a laboratory measurement. Please verify on site before acting on it.",
    ]
    return "\n".join(lines)


def _decode_photo(photo: Optional[str]) -> Optional[Tuple[bytes, str]]:
    if not photo:
        return None
    match = DATA_URI.match(photo.strip())
    if not match:
        return None
    try:
        content = base64.b64decode(match.group("payload"), validate=True)
    except (binascii.Error, ValueError):
        return None
    if not content or len(content) > MAX_PHOTO_BYTES:
        return None
    kind = match.group("kind").lower()
    suffix = {"jpeg": ".jpg", "jpg": ".jpg", "png": ".png", "webp": ".webp"}.get(kind, ".bin")
    return content, suffix


def _store(
    reference: str, request: ContaminationReportRequest, summary: str, water_body: Optional[str] = None
) -> Tuple[bool, Optional[str]]:
    """Append the record to the monthly log. Returns (stored, photo path)."""
    root = Path(settings.reports_path).expanduser()
    photo_path: Optional[str] = None
    try:
        root.mkdir(parents=True, exist_ok=True)
        decoded = _decode_photo(request.photo)
        if decoded is not None:
            content, suffix = decoded
            photos = root / "photos"
            photos.mkdir(parents=True, exist_ok=True)
            target = photos / f"{reference}{suffix}"
            target.write_bytes(content)
            photo_path = str(target)

        record = {
            "reference": reference,
            "createdAt": datetime.now(timezone.utc).isoformat(),
            "source": request.source,
            "location": request.location.model_dump(mode="json", by_alias=True),
            "match": request.match.model_dump(mode="json", by_alias=True),
            "waterRiskLevel": request.water_risk_level,
            "waterRiskScore": request.water_risk_score,
            "note": request.note,
            "contact": request.contact,
            "photoPath": photo_path,
            "waterBody": water_body,
            "summary": summary,
        }
        log = root / f"contamination-{datetime.now(timezone.utc):%Y-%m}.jsonl"
        with _write_lock:
            with log.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(record, ensure_ascii=False) + "\n")
        return True, photo_path
    except OSError:
        return False, photo_path


def _forward(
    reference: str, request: ContaminationReportRequest, summary: str, water_body: Optional[str] = None
) -> Tuple[str, Optional[str], str]:
    """POST to the configured destination. Returns (status, delivered_to, message)."""
    url = settings.authority_webhook_url
    if not url:
        return (
            "recorded",
            None,
            (
                "Saved to this backend's report log. No forwarding destination is configured, so "
                "nothing was transmitted to any authority — copy or download the report and send it "
                "yourself. (Set ECOSENTINEL_AUTHORITY_WEBHOOK_URL to enable forwarding.)"
            ),
        )

    try:
        import httpx
    except ImportError:  # pragma: no cover
        return "forward_failed", None, "Saved locally, but httpx is not installed, so it could not be forwarded."

    headers = {"Content-Type": "application/json"}
    if settings.authority_webhook_token:
        headers["Authorization"] = f"Bearer {settings.authority_webhook_token}"
    payload = {
        "reference": reference,
        "summary": summary,
        "observedAt": request.observed_at.isoformat(),
        "source": request.source,
        "location": request.location.model_dump(mode="json", by_alias=True),
        "match": request.match.model_dump(mode="json", by_alias=True),
        "waterRiskLevel": request.water_risk_level,
        "waterRiskScore": request.water_risk_score,
        "note": request.note,
        "contact": request.contact,
        "waterBody": water_body,
    }
    # Only the host is echoed back: the configured URL may carry a token in its path or query.
    host = None
    try:
        from urllib.parse import urlsplit

        host = urlsplit(url).hostname
        response = httpx.post(url, json=payload, headers=headers, timeout=settings.authority_timeout_seconds)
    except Exception as exc:
        return (
            "forward_failed",
            None,
            f"Saved to this backend's report log, but forwarding failed ({exc.__class__.__name__}). Send it yourself.",
        )

    if 200 <= response.status_code < 300:
        return (
            "forwarded",
            host,
            f"Forwarded to {settings.authority_name} ({host}), which accepted it with HTTP {response.status_code}.",
        )
    return (
        "forward_failed",
        host,
        (
            f"Saved to this backend's report log, but {host} rejected it with HTTP "
            f"{response.status_code}. Nothing reached an authority — send the report yourself."
        ),
    )


def _identify_water_body(request: ContaminationReportRequest) -> Optional[str]:
    """Name the water body being reported, so a recipient knows WHICH lake or drain this is.

    Reverse geocoding only mentions water when the reported point happens to sit on it, which for
    a photo taken from a bank it usually does not. Overpass answers the question directly. The
    reporter's own `waterFeature` always wins; this only fills a gap, and a lookup failure simply
    leaves the field out rather than blocking the report.
    """
    if request.location.water_feature:
        return request.location.water_feature
    feature = nearest_water_body(request.location.latitude, request.location.longitude)
    if feature is None:
        return None
    distance_m = round(feature.distance_km * 1000)
    return f"{feature.display_name} ({feature.label}, ~{distance_m} m away, OSM {feature.osm_id})"


def submit_report(request: ContaminationReportRequest) -> ContaminationReportReceipt:
    reference = _reference()
    water_body = _identify_water_body(request)
    summary = build_summary(request, reference, water_body)
    stored, _photo_path = _store(reference, request, summary, water_body)
    status, delivered_to, message = _forward(reference, request, summary, water_body)
    if not stored:
        message = f"Could not write to the report log at {settings.reports_path}. " + message
    return ContaminationReportReceipt(
        reference=reference,
        status=status,  # type: ignore[arg-type]
        message=message,
        created_at=datetime.now(timezone.utc),
        stored=stored,
        delivered_to=delivered_to,
        summary=summary,
    )
