import { pct } from '../lib/format';
import type { AnalysisResult, Measurement } from '../types/agents';

const line = (char = '─', length = 64) => char.repeat(length);

function measurementLines(measurements: Measurement[]): string[] {
  return measurements.map((m) => {
    const value = m.value === null ? 'missing' : `${m.value}${m.unit ? ` ${m.unit}` : ''}`;
    const threshold = m.threshold !== null ? `  (limit ${m.threshold}${m.unit ? ` ${m.unit}` : ''})` : '';
    return `  • ${m.label.padEnd(18)} ${value}${threshold}`;
  });
}

export function buildReportJson(result: AnalysisResult): string {
  return JSON.stringify(
    {
      report: 'EcoSentinel AI — Environmental Risk Report',
      generatedAt: new Date().toISOString(),
      location: result.location,
      overallRisk: result.coordinator.overallRiskLevel,
      overallScore: result.coordinator.overallScore,
      confidence: result.coordinator.confidence,
      analysis: result,
    },
    null,
    2,
  );
}

export function buildReportText(result: AnalysisResult): string {
  const { air, water, waste, coordinator } = result;
  const out: string[] = [
    'ECOSENTINEL AI — ENVIRONMENTAL RISK REPORT',
    line('═'),
    `Location:      ${result.location}`,
    `Generated:     ${new Date().toLocaleString('en-GB')}`,
    `Analysis ID:   ${result.analysisId} (${result.mode} mode)`,
    `Overall risk:  ${coordinator.overallRiskLevel} (${pct(coordinator.overallScore)}%)`,
    `Confidence:    ${pct(coordinator.confidence)}%`,
    '',
  ];

  out.push('AIR ASSESSMENT', line());
  if (air) {
    out.push(`Risk: ${air.riskLevel} (${pct(air.riskScore)}%) · Station: ${air.stationName} · AQI ${air.aqi ?? '—'} ${air.aqiCategory ?? ''}`);
    out.push(...measurementLines(air.measurements));
    air.findings.forEach((f) => out.push(`  ! ${f.label} — ${f.detail}`));
  } else out.push('Air agent report unavailable.');
  out.push('');

  out.push('WATER ASSESSMENT', line());
  if (water) {
    out.push(`Risk: ${water.riskLevel} (${pct(water.riskScore)}%) · Sensor: ${water.sensorName} (${water.sensorStatus})`);
    out.push(...measurementLines(water.measurements));
    water.findings.forEach((f) => out.push(`  ! ${f.label} — ${f.detail}`));
    water.warnings.forEach((w) => out.push(`  ⚠ ${w}`));
  } else out.push('Water agent report unavailable.');
  out.push('');

  out.push('WASTE ASSESSMENT', line());
  if (waste) {
    out.push(`Risk: ${waste.riskLevel} (${pct(waste.riskScore)}%) · Source: ${waste.sourceName} · Model: ${waste.model}`);
    out.push(`  • Detected objects   ${waste.totalObjects}`);
    out.push(`  • Plastic / Paper / Other   ${waste.counts.plastic} / ${waste.counts.paper} / ${waste.counts.other}`);
    waste.findings.forEach((f) => out.push(`  ! ${f.label} — ${f.detail}`));
  } else out.push('Waste agent report unavailable.');
  out.push('');

  out.push('CROSS-SIGNAL REASONING', line(), coordinator.reasoning, '');
  coordinator.crossSignalInsights.forEach((insight) => out.push(`  → ${insight}`));
  out.push('', 'Key contributing factors:');
  coordinator.contributingFactors.forEach((f) => out.push(`  • ${f.label} (${f.agent}) — ${f.detail}`));
  out.push('');

  out.push('RECOMMENDED ACTIONS', line());
  coordinator.recommendations.forEach((r) => {
    out.push(`  P${r.priority} [${r.urgency}] ${r.title}`);
    out.push(`     ${r.explanation}`);
  });
  out.push('', line('═'), 'Generated by EcoSentinel AI multi-agent system.');
  return out.join('\n');
}

export function reportFilename(result: AnalysisResult, extension: 'json' | 'txt') {
  const date = result.completedAt.slice(0, 10);
  return `ecosentinel-report-${result.location.toLowerCase().replace(/\s+/g, '-')}-${date}.${extension}`;
}

export function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
