"""Train a PROVISIONAL floating-litter detector on the audited TUD-GV split.

    python training/water/train_water_detector.py --epochs 60
    python training/water/train_water_detector.py --prepare-only   # build the split, train nothing

WHY THIS EXISTS
---------------
The production water detector is COCO-pretrained YOLOv8n. Measured on `image copy 3.png` — a
canal surface packed with plastic bottles — it returns **zero** detections at the production
threshold of 0.25, and its only hypotheses below that are `bird` (0.089) and `kite` (0.015). It
never proposes `bottle` at any threshold, despite `bottle` being a COCO class. That is a domain
failure, not a threshold failure: COCO bottles are upright, isolated and close; floating litter is
small, densely packed, partially submerged and viewed obliquely from distance.

WHAT THIS DOES NOT DO
---------------------
It does not modify `water_datasets/TUD-GV`. The split is materialised into a separate directory
as **symlinks**, so the audited source stays byte-identical and the 1,501 images are not copied.

It does not overwrite the production detector. Weights land in `runs/water/litter_detector/` and
are promoted only by an explicit config change, only if the evaluation supports it.

THE SPLIT IS SESSION-LEVEL, AND THAT IS THE POINT
-------------------------------------------------
TUD-GV frames are subsampled video: 34.78% of images have a near-duplicate at dHash <= 2, and
98.3% of those pairs are within the same recording session. A random frame split would put a
frame and its near-twin either side of the boundary and report a test score that is largely
memorisation. The split used here comes from `TUDGV_SPLIT_MANIFEST.json`, which groups by
connected components of (session UNION near-duplicate) — so this script only reads it, and never
invents a split of its own.
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "water_datasets" / "TUD-GV"
MANIFEST = REPO / "runs" / "water" / "dataset_comparison" / "TUDGV_SPLIT_MANIFEST.json"
BUILD = REPO / "runs" / "water" / "tudgv_yolo"
OUTPUT = REPO / "runs" / "water"
RUN_NAME = "litter_detector"


def session_of(stem: str) -> str:
    """`exp11_102` -> `exp11`.

    Split on the FIRST underscore only. `exp1`, `exp11` and `exp121` are different sessions, and
    a prefix match would silently merge them across the split boundary — reintroducing exactly
    the leakage the manifest exists to prevent.
    """
    return stem.split("_", 1)[0]


def load_splits() -> dict:
    if not MANIFEST.is_file():
        sys.exit(f"Split manifest not found at {MANIFEST}. It is the only permitted split.")
    manifest = json.loads(MANIFEST.read_text())
    return {name: set(entry["sessions"]) for name, entry in manifest["splits"].items()}


def prepare(force: bool = False) -> dict:
    """Materialise the manifest split as a YOLO dataset of symlinks."""
    splits = load_splits()
    session_to_split = {
        session: name for name, sessions in splits.items() for session in sessions
    }

    if BUILD.exists() and force:
        shutil.rmtree(BUILD)

    counts = {name: {"images": 0, "boxes": 0} for name in splits}
    unassigned = []

    images = sorted((SOURCE / "images").glob("*.jpg"))
    if not images:
        sys.exit(f"No images found under {SOURCE / 'images'}.")

    for image in images:
        stem = image.stem
        split = session_to_split.get(session_of(stem))
        if split is None:
            # A session the manifest does not place is DROPPED, not guessed into a split.
            unassigned.append(stem)
            continue

        label = SOURCE / "labels_txt" / f"{stem}.txt"
        if not label.is_file():
            continue

        image_dir = BUILD / split / "images"
        label_dir = BUILD / split / "labels"
        image_dir.mkdir(parents=True, exist_ok=True)
        label_dir.mkdir(parents=True, exist_ok=True)

        image_link = image_dir / image.name
        label_link = label_dir / label.name
        for link, target in ((image_link, image), (label_link, label)):
            if link.is_symlink() or link.exists():
                link.unlink()
            # Symlink, not copy: the audited source must stay the single copy on disk.
            link.symlink_to(target)

        counts[split]["images"] += 1
        counts[split]["boxes"] += sum(
            1 for line in label.read_text().splitlines() if line.strip()
        )

    data_yaml = BUILD / "data.yaml"
    data_yaml.write_text(
        "# Generated by training/water/train_water_detector.py from TUDGV_SPLIT_MANIFEST.json.\n"
        "# Session-level split. Do not edit by hand; do not re-split randomly.\n"
        f"path: {BUILD}\n"
        "train: train/images\n"
        "val: val/images\n"
        "test: test/images\n"
        "nc: 1\n"
        "names: [litter]\n"
    )

    print(f"Split materialised at {BUILD}")
    for name in ("train", "val", "test"):
        entry = counts.get(name, {"images": 0, "boxes": 0})
        print(f"  {name:5} {entry['images']:5} images  {entry['boxes']:6} boxes")
    if unassigned:
        print(f"  {len(unassigned)} image(s) in sessions the manifest does not place — dropped")
    return counts


def train(args, counts: dict) -> Path:
    try:
        from ultralytics import YOLO
    except ImportError:
        sys.exit("ultralytics is required to train. pip install ultralytics")

    import torch

    device = args.device
    if device == "auto":
        if torch.backends.mps.is_available():
            device = "mps"
        elif torch.cuda.is_available():
            device = "0"
        else:
            device = "cpu"

    print(f"\nTraining YOLOv8n · {args.epochs} epochs · imgsz {args.imgsz} · device {device}")
    model = YOLO("yolov8n.pt")  # COCO-pretrained backbone, fine-tuned to one class
    model.train(
        data=str(BUILD / "data.yaml"),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=device,
        project=str(OUTPUT),
        name=RUN_NAME,
        exist_ok=True,
        seed=args.seed,
        patience=args.patience,
        val=True,
        plots=True,
        verbose=True,
    )

    weights = OUTPUT / RUN_NAME / "weights" / "best.pt"
    manifest = {
        "model": "yolov8n",
        "role": "PROVISIONAL WATER LITTER DETECTOR",
        "promoted": False,
        "pretrained": "yolov8n.pt (COCO)",
        "classes": ["litter"],
        "dataset": "TUD-GV",
        "split_source": str(MANIFEST.relative_to(REPO)),
        "split_unit": "session-level (connected components of session UNION dHash<=2)",
        "counts": counts,
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "seed": args.seed,
        "patience": args.patience,
        "device": device,
        "weights": str(weights.relative_to(REPO)) if weights.is_file() else None,
        "limitations": [
            "TUD-GV contains ZERO verified-clean-water frames, so the false-positive rate on "
            "clean water is unmeasured. This detector must not be described as validated for "
            "production water-pollution detection.",
            "Single class 'litter'. It makes no distinction between bottle, bag or debris.",
            "Trained on one canal-surface domain; generalisation to other waters is unmeasured.",
        ],
    }
    (OUTPUT / RUN_NAME / "training_manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"\nWeights: {weights}")
    return weights


def evaluate(weights: Path, args) -> None:
    """Held-out TEST split. Reported separately from val, which drove checkpoint selection."""
    from ultralytics import YOLO

    print("\nEvaluating on the held-out TEST split (never used for training or selection)")
    model = YOLO(str(weights))
    metrics = model.val(
        data=str(BUILD / "data.yaml"),
        split="test",
        imgsz=args.imgsz,
        device=args.device if args.device != "auto" else None,
        project=str(OUTPUT),
        name=f"{RUN_NAME}_test",
        exist_ok=True,
        plots=True,
    )
    box = metrics.box
    summary = {
        "split": "test",
        "precision": round(float(box.mp), 4),
        "recall": round(float(box.mr), 4),
        "map50": round(float(box.map50), 4),
        "map50_95": round(float(box.map), 4),
    }
    (OUTPUT / RUN_NAME / "test_metrics.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps(summary, indent=2))


def main() -> int:
    parser = argparse.ArgumentParser(description="Train a provisional TUD-GV litter detector")
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--patience", type=int, default=15)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--prepare-only", action="store_true")
    parser.add_argument("--force", action="store_true", help="rebuild the split directory")
    args = parser.parse_args()

    counts = prepare(force=args.force)
    if args.prepare_only:
        return 0

    weights = train(args, counts)
    if weights.is_file():
        evaluate(weights, args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
